### ISSUE TITLE
Configure manager-style class to handle direct connection support

### ISSUE THREAD

**Issue by shouples** [confluentinc/vscode#422]
Implementation details TBD based on UI/UX input and number of auth mechanisms that need to be supported.

Basics:
- [x] Should **_not_** extend the existing [ConfluentCloudAuthProvider](https://github.com/confluentinc/vscode/blob/main/src/authProvider.ts#L24)
- [ ] Should support multiple accounts/connections
- [ ] Should integrate with the VS Code secret store for user credentials
- [x] Should use unique connection IDs to associate with any resources queried (we currently use static constants for [local and CCloud connections](https://github.com/confluentinc/vscode/blob/main/src/constants.ts#L59-L79))
- [x] Should include an event listener to watch extension settings when direct connection setting is toggled (https://github.com/confluentinc/vscode/issues/624) and update VS Code UI contextValue(s) appropriately
- [ ] Should be the main handler between the connection webview form, the secret store, and the sidecar (follow-on issue to handle a direct connection `ResourceLoader` variant to handle dynamic connection IDs)

https://github.com/confluentinc/vscode/issues/623 covers how these connections are displayed to the user in the Resources view in the extension sidebar.
